/********************************************************************************
** Form generated from reading UI file 'MainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.3.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindowClass
{
public:
    QAction *actionOpen;
    QAction *actionExit;
    QAction *actionWrite_Device;
    QAction *actionErase_Device;
    QAction *action_About;
    QAction *action_Verify_Device;
    QAction *action_Settings;
    QAction *actionReset_Device;
    QAction *actionBlank_Check;
    QAction *actionAgain;
    QAction *actionReadEEPROM;
    QAction *actionWriteEEPROM;
    QAction *actionRadioButtonBlink;
    QAction *actionRadioButtonBreath;
    QAction *actionRadioButtonSparkle;
    QAction *actionRadioButtonTwinkle;
    QAction *actionRadioButtonToneEnable;
    QAction *actionRadioSignalStrength;
    QAction *actionReadFile;
    QAction *actionSaveFile;
    QAction *actionRadioToneDecodeDisabled;
    QAction *actionRadioButtonPWMDisable;
    QAction *actionRadioButtonPWMEnable;
    QAction *actionRadioButtonRGBEnable;
    QAction *actionResetButton;
    QWidget *centralWidget;
    QPlainTextEdit *plainTextEdit;
    QPushButton *ReadEEPROM;
    QPushButton *WriteEEPROM;
    QLabel *label;
    QLineEdit *FirmwareVersion;
    QLabel *label_2;
    QDoubleSpinBox *RadioFrequency;
    QLineEdit *DeviceAddress;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLineEdit *GroupAddress1;
    QLineEdit *GroupAddress2;
    QLineEdit *GroupAddress3;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLineEdit *Tone1;
    QLineEdit *Tone2;
    QLineEdit *Tone3;
    QLabel *label_10;
    QLineEdit *Tone6;
    QLineEdit *Tone5;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *Tone4;
    QLineEdit *NumTones;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *Hysteresis;
    QLineEdit *ToneSpacing;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *Threshold;
    QFrame *frame;
    QLabel *label_17;
    QFrame *frame_2;
    QLabel *label_18;
    QFrame *frame_3;
    QLabel *label_23;
    QFrame *frame_4;
    QFrame *OutputModeFrame;
    QLabel *label_24;
    QRadioButton *RadioButtonPWMDisable;
    QLabel *label_25;
    QRadioButton *RadioButtonPWMEnable;
    QLabel *label_26;
    QRadioButton *RadioButtonRGBEnable;
    QFrame *frame_5;
    QFrame *frame_7;
    QLabel *label_21;
    QPushButton *SaveFile;
    QPushButton *ReadFile;
    QFrame *StartModeFrame;
    QRadioButton *radioButtonBreath;
    QRadioButton *radioButtonBlink;
    QLabel *label_19;
    QRadioButton *radioToneDecodeDisabled;
    QLineEdit *PatternOn;
    QRadioButton *radioButtonSparkle;
    QLabel *label_20;
    QLineEdit *PatternOff;
    QRadioButton *radioButtonToneEnable;
    QRadioButton *radioButtonSignalStrength;
    QRadioButton *radioButtonTwinkle;
    QPushButton *ResetButton;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuProgrammer;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindowClass)
    {
        if (MainWindowClass->objectName().isEmpty())
            MainWindowClass->setObjectName(QStringLiteral("MainWindowClass"));
        MainWindowClass->setEnabled(true);
        MainWindowClass->resize(680, 750);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindowClass->sizePolicy().hasHeightForWidth());
        MainWindowClass->setSizePolicy(sizePolicy);
        MainWindowClass->setMinimumSize(QSize(680, 750));
        MainWindowClass->setMaximumSize(QSize(680, 750));
        QFont font;
        font.setPointSize(10);
        MainWindowClass->setFont(font);
        MainWindowClass->setWindowTitle(QStringLiteral("Linzer Schnitte EEPROM Editor"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/MainWindow/img/LS_Logo.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindowClass->setWindowIcon(icon);
        MainWindowClass->setWindowOpacity(1);
        actionOpen = new QAction(MainWindowClass);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        actionOpen->setEnabled(false);
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/MainWindow/img/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen->setIcon(icon1);
        actionExit = new QAction(MainWindowClass);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionWrite_Device = new QAction(MainWindowClass);
        actionWrite_Device->setObjectName(QStringLiteral("actionWrite_Device"));
        actionWrite_Device->setEnabled(false);
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/MainWindow/img/writetqfp.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionWrite_Device->setIcon(icon2);
        actionErase_Device = new QAction(MainWindowClass);
        actionErase_Device->setObjectName(QStringLiteral("actionErase_Device"));
        actionErase_Device->setEnabled(false);
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/MainWindow/img/erasetqfp.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionErase_Device->setIcon(icon3);
        actionErase_Device->setVisible(false);
        action_About = new QAction(MainWindowClass);
        action_About->setObjectName(QStringLiteral("action_About"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/MainWindow/img/help.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_About->setIcon(icon4);
        action_Verify_Device = new QAction(MainWindowClass);
        action_Verify_Device->setObjectName(QStringLiteral("action_Verify_Device"));
        action_Verify_Device->setEnabled(false);
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/MainWindow/img/verify.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Verify_Device->setIcon(icon5);
        action_Verify_Device->setVisible(false);
        action_Settings = new QAction(MainWindowClass);
        action_Settings->setObjectName(QStringLiteral("action_Settings"));
        action_Settings->setEnabled(false);
        actionReset_Device = new QAction(MainWindowClass);
        actionReset_Device->setObjectName(QStringLiteral("actionReset_Device"));
        actionReset_Device->setEnabled(false);
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/MainWindow/img/Reset.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionReset_Device->setIcon(icon6);
        actionBlank_Check = new QAction(MainWindowClass);
        actionBlank_Check->setObjectName(QStringLiteral("actionBlank_Check"));
        actionBlank_Check->setEnabled(false);
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/MainWindow/img/BlankCheck.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBlank_Check->setIcon(icon7);
        actionBlank_Check->setVisible(false);
        actionAgain = new QAction(MainWindowClass);
        actionAgain->setObjectName(QStringLiteral("actionAgain"));
        actionReadEEPROM = new QAction(MainWindowClass);
        actionReadEEPROM->setObjectName(QStringLiteral("actionReadEEPROM"));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/MainWindow/img/LS_Logo.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        icon8.addFile(QStringLiteral(":/MainWindow/img/stop.png"), QSize(), QIcon::Normal, QIcon::On);
        actionReadEEPROM->setIcon(icon8);
        actionWriteEEPROM = new QAction(MainWindowClass);
        actionWriteEEPROM->setObjectName(QStringLiteral("actionWriteEEPROM"));
        actionWriteEEPROM->setIcon(icon);
        actionRadioButtonBlink = new QAction(MainWindowClass);
        actionRadioButtonBlink->setObjectName(QStringLiteral("actionRadioButtonBlink"));
        actionRadioButtonBlink->setCheckable(true);
        actionRadioButtonBreath = new QAction(MainWindowClass);
        actionRadioButtonBreath->setObjectName(QStringLiteral("actionRadioButtonBreath"));
        actionRadioButtonBreath->setCheckable(true);
        actionRadioButtonSparkle = new QAction(MainWindowClass);
        actionRadioButtonSparkle->setObjectName(QStringLiteral("actionRadioButtonSparkle"));
        actionRadioButtonSparkle->setCheckable(true);
        actionRadioButtonTwinkle = new QAction(MainWindowClass);
        actionRadioButtonTwinkle->setObjectName(QStringLiteral("actionRadioButtonTwinkle"));
        actionRadioButtonTwinkle->setCheckable(true);
        actionRadioButtonToneEnable = new QAction(MainWindowClass);
        actionRadioButtonToneEnable->setObjectName(QStringLiteral("actionRadioButtonToneEnable"));
        actionRadioButtonToneEnable->setCheckable(true);
        actionRadioSignalStrength = new QAction(MainWindowClass);
        actionRadioSignalStrength->setObjectName(QStringLiteral("actionRadioSignalStrength"));
        actionRadioSignalStrength->setCheckable(true);
        actionReadFile = new QAction(MainWindowClass);
        actionReadFile->setObjectName(QStringLiteral("actionReadFile"));
        actionSaveFile = new QAction(MainWindowClass);
        actionSaveFile->setObjectName(QStringLiteral("actionSaveFile"));
        actionRadioToneDecodeDisabled = new QAction(MainWindowClass);
        actionRadioToneDecodeDisabled->setObjectName(QStringLiteral("actionRadioToneDecodeDisabled"));
        actionRadioToneDecodeDisabled->setCheckable(true);
        actionRadioButtonPWMDisable = new QAction(MainWindowClass);
        actionRadioButtonPWMDisable->setObjectName(QStringLiteral("actionRadioButtonPWMDisable"));
        actionRadioButtonPWMDisable->setCheckable(true);
        actionRadioButtonPWMEnable = new QAction(MainWindowClass);
        actionRadioButtonPWMEnable->setObjectName(QStringLiteral("actionRadioButtonPWMEnable"));
        actionRadioButtonPWMEnable->setCheckable(true);
        actionRadioButtonRGBEnable = new QAction(MainWindowClass);
        actionRadioButtonRGBEnable->setObjectName(QStringLiteral("actionRadioButtonRGBEnable"));
        actionRadioButtonRGBEnable->setCheckable(true);
        actionResetButton = new QAction(MainWindowClass);
        actionResetButton->setObjectName(QStringLiteral("actionResetButton"));
        centralWidget = new QWidget(MainWindowClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        plainTextEdit = new QPlainTextEdit(centralWidget);
        plainTextEdit->setObjectName(QStringLiteral("plainTextEdit"));
        plainTextEdit->setEnabled(true);
        plainTextEdit->setGeometry(QRect(10, 570, 661, 141));
        QSizePolicy sizePolicy1(QSizePolicy::Maximum, QSizePolicy::Maximum);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(plainTextEdit->sizePolicy().hasHeightForWidth());
        plainTextEdit->setSizePolicy(sizePolicy1);
        plainTextEdit->setMinimumSize(QSize(500, 0));
        QFont font1;
        font1.setFamily(QStringLiteral("Monospace"));
        plainTextEdit->setFont(font1);
        plainTextEdit->setReadOnly(true);
        ReadEEPROM = new QPushButton(centralWidget);
        ReadEEPROM->setObjectName(QStringLiteral("ReadEEPROM"));
        ReadEEPROM->setGeometry(QRect(150, 530, 131, 24));
        sizePolicy.setHeightForWidth(ReadEEPROM->sizePolicy().hasHeightForWidth());
        ReadEEPROM->setSizePolicy(sizePolicy);
        ReadEEPROM->setIcon(icon);
        WriteEEPROM = new QPushButton(centralWidget);
        WriteEEPROM->setObjectName(QStringLiteral("WriteEEPROM"));
        WriteEEPROM->setEnabled(true);
        WriteEEPROM->setGeometry(QRect(290, 530, 131, 23));
        WriteEEPROM->setIcon(icon);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 5, 171, 21));
        QFont font2;
        font2.setPointSize(14);
        label->setFont(font2);
        FirmwareVersion = new QLineEdit(centralWidget);
        FirmwareVersion->setObjectName(QStringLiteral("FirmwareVersion"));
        FirmwareVersion->setEnabled(false);
        FirmwareVersion->setGeometry(QRect(190, 0, 131, 31));
        QFont font3;
        font3.setPointSize(16);
        FirmwareVersion->setFont(font3);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(330, 0, 241, 31));
        label_2->setFont(font2);
        RadioFrequency = new QDoubleSpinBox(centralWidget);
        RadioFrequency->setObjectName(QStringLiteral("RadioFrequency"));
        RadioFrequency->setGeometry(QRect(570, 0, 101, 31));
        QPalette palette;
        QBrush brush(QColor(255, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        QBrush brush2(QColor(123, 123, 123, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        RadioFrequency->setPalette(palette);
        QFont font4;
        font4.setPointSize(16);
        font4.setBold(false);
        font4.setWeight(50);
        RadioFrequency->setFont(font4);
        RadioFrequency->setMinimum(88);
        RadioFrequency->setMaximum(108);
        RadioFrequency->setSingleStep(0.1);
        RadioFrequency->setValue(108);
        DeviceAddress = new QLineEdit(centralWidget);
        DeviceAddress->setObjectName(QStringLiteral("DeviceAddress"));
        DeviceAddress->setGeometry(QRect(240, 360, 61, 31));
        QPalette palette1;
        QBrush brush3(QColor(0, 0, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        DeviceAddress->setPalette(palette1);
        DeviceAddress->setFont(font2);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(50, 360, 151, 31));
        label_3->setFont(font2);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(50, 400, 161, 31));
        label_4->setFont(font2);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(50, 440, 161, 31));
        label_5->setFont(font2);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(50, 480, 161, 31));
        label_6->setFont(font2);
        GroupAddress1 = new QLineEdit(centralWidget);
        GroupAddress1->setObjectName(QStringLiteral("GroupAddress1"));
        GroupAddress1->setGeometry(QRect(240, 400, 61, 31));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        GroupAddress1->setPalette(palette2);
        GroupAddress1->setFont(font2);
        GroupAddress2 = new QLineEdit(centralWidget);
        GroupAddress2->setObjectName(QStringLiteral("GroupAddress2"));
        GroupAddress2->setGeometry(QRect(240, 440, 61, 31));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        GroupAddress2->setPalette(palette3);
        GroupAddress2->setFont(font2);
        GroupAddress3 = new QLineEdit(centralWidget);
        GroupAddress3->setObjectName(QStringLiteral("GroupAddress3"));
        GroupAddress3->setGeometry(QRect(240, 480, 61, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        GroupAddress3->setPalette(palette4);
        GroupAddress3->setFont(font2);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 220, 91, 31));
        label_7->setFont(font2);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 300, 81, 31));
        label_8->setFont(font2);
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 260, 81, 31));
        label_9->setFont(font2);
        Tone1 = new QLineEdit(centralWidget);
        Tone1->setObjectName(QStringLiteral("Tone1"));
        Tone1->setGeometry(QRect(90, 220, 71, 31));
        QPalette palette5;
        QBrush brush4(QColor(0, 85, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        Tone1->setPalette(palette5);
        Tone1->setFont(font2);
        Tone2 = new QLineEdit(centralWidget);
        Tone2->setObjectName(QStringLiteral("Tone2"));
        Tone2->setGeometry(QRect(90, 260, 71, 31));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        Tone2->setPalette(palette6);
        Tone2->setFont(font2);
        Tone3 = new QLineEdit(centralWidget);
        Tone3->setObjectName(QStringLiteral("Tone3"));
        Tone3->setGeometry(QRect(90, 300, 71, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        Tone3->setPalette(palette7);
        Tone3->setFont(font2);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(170, 260, 81, 31));
        label_10->setFont(font2);
        Tone6 = new QLineEdit(centralWidget);
        Tone6->setObjectName(QStringLiteral("Tone6"));
        Tone6->setGeometry(QRect(240, 300, 71, 31));
        Tone6->setFont(font2);
        Tone5 = new QLineEdit(centralWidget);
        Tone5->setObjectName(QStringLiteral("Tone5"));
        Tone5->setGeometry(QRect(240, 260, 71, 31));
        Tone5->setFont(font2);
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(170, 220, 91, 31));
        label_11->setFont(font2);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(170, 300, 81, 31));
        label_12->setFont(font2);
        Tone4 = new QLineEdit(centralWidget);
        Tone4->setObjectName(QStringLiteral("Tone4"));
        Tone4->setEnabled(true);
        Tone4->setGeometry(QRect(240, 220, 71, 31));
        Tone4->setFont(font2);
        NumTones = new QLineEdit(centralWidget);
        NumTones->setObjectName(QStringLiteral("NumTones"));
        NumTones->setEnabled(false);
        NumTones->setGeometry(QRect(240, 60, 71, 31));
        NumTones->setFont(font2);
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 180, 181, 31));
        label_13->setFont(font2);
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(20, 100, 171, 31));
        label_14->setFont(font2);
        Hysteresis = new QLineEdit(centralWidget);
        Hysteresis->setObjectName(QStringLiteral("Hysteresis"));
        Hysteresis->setGeometry(QRect(240, 180, 71, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        Hysteresis->setPalette(palette8);
        Hysteresis->setFont(font2);
        ToneSpacing = new QLineEdit(centralWidget);
        ToneSpacing->setObjectName(QStringLiteral("ToneSpacing"));
        ToneSpacing->setEnabled(false);
        ToneSpacing->setGeometry(QRect(240, 100, 71, 31));
        ToneSpacing->setFont(font2);
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(20, 140, 181, 31));
        label_15->setFont(font2);
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 60, 171, 31));
        label_16->setFont(font2);
        Threshold = new QLineEdit(centralWidget);
        Threshold->setObjectName(QStringLiteral("Threshold"));
        Threshold->setGeometry(QRect(240, 140, 71, 31));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        Threshold->setPalette(palette9);
        Threshold->setFont(font2);
        frame = new QFrame(centralWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 30, 321, 21));
        QPalette palette10;
        QBrush brush5(QColor(255, 255, 255, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        QBrush brush6(QColor(255, 170, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush6);
        QBrush brush7(QColor(255, 85, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        frame->setPalette(palette10);
        QFont font5;
        font5.setPointSize(13);
        frame->setFont(font5);
        frame->setAutoFillBackground(false);
        frame->setFrameShape(QFrame::Panel);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(2);
        frame->setMidLineWidth(1);
        label_17 = new QLabel(frame);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(50, 0, 211, 20));
        QSizePolicy sizePolicy2(QSizePolicy::Maximum, QSizePolicy::Fixed);
        sizePolicy2.setHorizontalStretch(0);
        sizePolicy2.setVerticalStretch(0);
        sizePolicy2.setHeightForWidth(label_17->sizePolicy().hasHeightForWidth());
        label_17->setSizePolicy(sizePolicy2);
        QPalette palette11;
        QBrush brush8(QColor(255, 0, 255, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush7);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Active, QPalette::NoRole, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::NoRole, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::NoRole, brush5);
        label_17->setPalette(palette11);
        label_17->setFont(font);
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(10, 340, 321, 21));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        frame_2->setPalette(palette12);
        frame_2->setAutoFillBackground(false);
        frame_2->setFrameShape(QFrame::Panel);
        frame_2->setFrameShadow(QFrame::Sunken);
        frame_2->setLineWidth(2);
        frame_2->setMidLineWidth(1);
        label_18 = new QLabel(frame_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(50, 0, 211, 20));
        sizePolicy2.setHeightForWidth(label_18->sizePolicy().hasHeightForWidth());
        label_18->setSizePolicy(sizePolicy2);
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush7);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette13.setBrush(QPalette::Active, QPalette::NoRole, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::NoRole, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::NoRole, brush5);
        label_18->setPalette(palette13);
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(340, 30, 331, 21));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        frame_3->setPalette(palette14);
        frame_3->setAutoFillBackground(false);
        frame_3->setFrameShape(QFrame::Panel);
        frame_3->setFrameShadow(QFrame::Sunken);
        frame_3->setLineWidth(2);
        frame_3->setMidLineWidth(1);
        label_23 = new QLabel(frame_3);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(100, 0, 101, 20));
        sizePolicy2.setHeightForWidth(label_23->sizePolicy().hasHeightForWidth());
        label_23->setSizePolicy(sizePolicy2);
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush7);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette15.setBrush(QPalette::Active, QPalette::NoRole, brush5);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush7);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette15.setBrush(QPalette::Inactive, QPalette::NoRole, brush5);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush7);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette15.setBrush(QPalette::Disabled, QPalette::NoRole, brush5);
        label_23->setPalette(palette15);
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(10, 50, 321, 291));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette16.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette16.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette16.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        frame_4->setPalette(palette16);
        frame_4->setFont(font5);
        frame_4->setAutoFillBackground(false);
        frame_4->setFrameShape(QFrame::Panel);
        frame_4->setFrameShadow(QFrame::Sunken);
        frame_4->setLineWidth(2);
        frame_4->setMidLineWidth(1);
        OutputModeFrame = new QFrame(centralWidget);
        OutputModeFrame->setObjectName(QStringLiteral("OutputModeFrame"));
        OutputModeFrame->setEnabled(true);
        OutputModeFrame->setGeometry(QRect(340, 50, 331, 151));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette17.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette17.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette17.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        OutputModeFrame->setPalette(palette17);
        OutputModeFrame->setFont(font5);
        OutputModeFrame->setAutoFillBackground(false);
        OutputModeFrame->setFrameShape(QFrame::Panel);
        OutputModeFrame->setFrameShadow(QFrame::Sunken);
        OutputModeFrame->setLineWidth(2);
        OutputModeFrame->setMidLineWidth(1);
        label_24 = new QLabel(OutputModeFrame);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(40, 30, 271, 16));
        label_24->setFont(font);
        RadioButtonPWMDisable = new QRadioButton(OutputModeFrame);
        RadioButtonPWMDisable->setObjectName(QStringLiteral("RadioButtonPWMDisable"));
        RadioButtonPWMDisable->setGeometry(QRect(10, 10, 311, 21));
        label_25 = new QLabel(OutputModeFrame);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(40, 70, 271, 16));
        label_25->setFont(font);
        RadioButtonPWMEnable = new QRadioButton(OutputModeFrame);
        RadioButtonPWMEnable->setObjectName(QStringLiteral("RadioButtonPWMEnable"));
        RadioButtonPWMEnable->setGeometry(QRect(10, 50, 311, 21));
        label_26 = new QLabel(OutputModeFrame);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(40, 110, 271, 16));
        label_26->setFont(font);
        RadioButtonRGBEnable = new QRadioButton(OutputModeFrame);
        RadioButtonRGBEnable->setObjectName(QStringLiteral("RadioButtonRGBEnable"));
        RadioButtonRGBEnable->setEnabled(false);
        RadioButtonRGBEnable->setGeometry(QRect(10, 90, 311, 21));
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(10, 360, 321, 161));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette18.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette18.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette18.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        frame_5->setPalette(palette18);
        frame_5->setFont(font5);
        frame_5->setAutoFillBackground(false);
        frame_5->setFrameShape(QFrame::Panel);
        frame_5->setFrameShadow(QFrame::Sunken);
        frame_5->setLineWidth(2);
        frame_5->setMidLineWidth(1);
        frame_7 = new QFrame(centralWidget);
        frame_7->setObjectName(QStringLiteral("frame_7"));
        frame_7->setGeometry(QRect(340, 200, 331, 21));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette19.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette19.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette19.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        frame_7->setPalette(palette19);
        frame_7->setAutoFillBackground(false);
        frame_7->setFrameShape(QFrame::Panel);
        frame_7->setFrameShadow(QFrame::Sunken);
        frame_7->setLineWidth(2);
        frame_7->setMidLineWidth(1);
        label_21 = new QLabel(frame_7);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(70, 0, 171, 20));
        label_21->setFont(font);
        SaveFile = new QPushButton(centralWidget);
        SaveFile->setObjectName(QStringLiteral("SaveFile"));
        SaveFile->setEnabled(true);
        SaveFile->setGeometry(QRect(430, 530, 111, 23));
        ReadFile = new QPushButton(centralWidget);
        ReadFile->setObjectName(QStringLiteral("ReadFile"));
        ReadFile->setEnabled(true);
        ReadFile->setGeometry(QRect(10, 530, 131, 23));
        ReadFile->setIcon(icon1);
        StartModeFrame = new QFrame(centralWidget);
        StartModeFrame->setObjectName(QStringLiteral("StartModeFrame"));
        StartModeFrame->setGeometry(QRect(340, 220, 331, 301));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette20.setBrush(QPalette::Active, QPalette::Midlight, brush5);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette20.setBrush(QPalette::Inactive, QPalette::Midlight, brush5);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette20.setBrush(QPalette::Disabled, QPalette::Midlight, brush5);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        StartModeFrame->setPalette(palette20);
        StartModeFrame->setFont(font5);
        StartModeFrame->setAutoFillBackground(false);
        StartModeFrame->setFrameShape(QFrame::Panel);
        StartModeFrame->setFrameShadow(QFrame::Sunken);
        StartModeFrame->setLineWidth(2);
        StartModeFrame->setMidLineWidth(1);
        radioButtonBreath = new QRadioButton(StartModeFrame);
        radioButtonBreath->setObjectName(QStringLiteral("radioButtonBreath"));
        radioButtonBreath->setGeometry(QRect(10, 180, 291, 31));
        radioButtonBreath->setFont(font5);
        radioButtonBreath->setAutoExclusive(true);
        radioButtonBlink = new QRadioButton(StartModeFrame);
        radioButtonBlink->setObjectName(QStringLiteral("radioButtonBlink"));
        radioButtonBlink->setGeometry(QRect(10, 140, 201, 31));
        radioButtonBlink->setFont(font5);
        radioButtonBlink->setAutoExclusive(true);
        label_19 = new QLabel(StartModeFrame);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(190, 120, 61, 20));
        label_19->setFont(font);
        radioToneDecodeDisabled = new QRadioButton(StartModeFrame);
        radioToneDecodeDisabled->setObjectName(QStringLiteral("radioToneDecodeDisabled"));
        radioToneDecodeDisabled->setGeometry(QRect(10, 40, 321, 31));
        radioToneDecodeDisabled->setFont(font5);
        radioToneDecodeDisabled->setAutoExclusive(true);
        PatternOn = new QLineEdit(StartModeFrame);
        PatternOn->setObjectName(QStringLiteral("PatternOn"));
        PatternOn->setGeometry(QRect(190, 140, 61, 31));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        PatternOn->setPalette(palette21);
        PatternOn->setFont(font2);
        radioButtonSparkle = new QRadioButton(StartModeFrame);
        radioButtonSparkle->setObjectName(QStringLiteral("radioButtonSparkle"));
        radioButtonSparkle->setGeometry(QRect(10, 220, 171, 31));
        radioButtonSparkle->setFont(font5);
        radioButtonSparkle->setAutoExclusive(true);
        label_20 = new QLabel(StartModeFrame);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(260, 120, 61, 20));
        label_20->setFont(font);
        PatternOff = new QLineEdit(StartModeFrame);
        PatternOff->setObjectName(QStringLiteral("PatternOff"));
        PatternOff->setGeometry(QRect(260, 140, 61, 31));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        PatternOff->setPalette(palette22);
        PatternOff->setFont(font2);
        radioButtonToneEnable = new QRadioButton(StartModeFrame);
        radioButtonToneEnable->setObjectName(QStringLiteral("radioButtonToneEnable"));
        radioButtonToneEnable->setGeometry(QRect(10, 10, 321, 31));
        radioButtonToneEnable->setFont(font5);
        radioButtonToneEnable->setAutoExclusive(true);
        radioButtonSignalStrength = new QRadioButton(StartModeFrame);
        radioButtonSignalStrength->setObjectName(QStringLiteral("radioButtonSignalStrength"));
        radioButtonSignalStrength->setGeometry(QRect(10, 70, 241, 31));
        radioButtonSignalStrength->setFont(font5);
        radioButtonSignalStrength->setAutoExclusive(true);
        radioButtonTwinkle = new QRadioButton(StartModeFrame);
        radioButtonTwinkle->setObjectName(QStringLiteral("radioButtonTwinkle"));
        radioButtonTwinkle->setGeometry(QRect(10, 260, 171, 31));
        radioButtonTwinkle->setFont(font5);
        radioButtonTwinkle->setAutoExclusive(true);
        ResetButton = new QPushButton(centralWidget);
        ResetButton->setObjectName(QStringLiteral("ResetButton"));
        ResetButton->setEnabled(true);
        ResetButton->setGeometry(QRect(550, 530, 111, 23));
        ResetButton->setIcon(icon6);
        MainWindowClass->setCentralWidget(centralWidget);
        StartModeFrame->raise();
        OutputModeFrame->raise();
        frame_4->raise();
        frame_5->raise();
        plainTextEdit->raise();
        ReadEEPROM->raise();
        WriteEEPROM->raise();
        label->raise();
        FirmwareVersion->raise();
        label_2->raise();
        RadioFrequency->raise();
        DeviceAddress->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        GroupAddress1->raise();
        GroupAddress2->raise();
        GroupAddress3->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        Tone1->raise();
        Tone2->raise();
        Tone3->raise();
        label_10->raise();
        Tone6->raise();
        Tone5->raise();
        label_11->raise();
        label_12->raise();
        Tone4->raise();
        NumTones->raise();
        label_13->raise();
        label_14->raise();
        Hysteresis->raise();
        ToneSpacing->raise();
        label_15->raise();
        label_16->raise();
        Threshold->raise();
        frame->raise();
        frame_2->raise();
        frame_3->raise();
        frame_7->raise();
        SaveFile->raise();
        ReadFile->raise();
        ResetButton->raise();
        menuBar = new QMenuBar(MainWindowClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 680, 27));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuProgrammer = new QMenu(menuBar);
        menuProgrammer->setObjectName(QStringLiteral("menuProgrammer"));
        MainWindowClass->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindowClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindowClass->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuProgrammer->menuAction());
        menuFile->addAction(actionOpen);
        menuFile->addSeparator();
        menuFile->addAction(actionExit);
        menuProgrammer->addSeparator();
        menuProgrammer->addAction(actionWrite_Device);
        menuProgrammer->addAction(action_Verify_Device);
        menuProgrammer->addAction(actionErase_Device);
        menuProgrammer->addAction(actionBlank_Check);
        menuProgrammer->addAction(actionReset_Device);
        menuProgrammer->addSeparator();
        menuProgrammer->addAction(action_Settings);

        retranslateUi(MainWindowClass);
        QObject::connect(ReadEEPROM, SIGNAL(clicked()), actionReadEEPROM, SLOT(trigger()));
        QObject::connect(WriteEEPROM, SIGNAL(clicked()), actionWriteEEPROM, SLOT(trigger()));
        QObject::connect(ReadFile, SIGNAL(clicked()), actionReadFile, SLOT(trigger()));
        QObject::connect(SaveFile, SIGNAL(clicked()), actionSaveFile, SLOT(trigger()));
        QObject::connect(RadioButtonPWMDisable, SIGNAL(clicked()), actionRadioButtonPWMDisable, SLOT(trigger()));
        QObject::connect(RadioButtonPWMEnable, SIGNAL(clicked()), actionRadioButtonPWMEnable, SLOT(trigger()));
        QObject::connect(RadioButtonRGBEnable, SIGNAL(clicked()), actionRadioButtonRGBEnable, SLOT(trigger()));
        QObject::connect(radioButtonToneEnable, SIGNAL(clicked()), actionRadioButtonToneEnable, SLOT(trigger()));
        QObject::connect(radioToneDecodeDisabled, SIGNAL(clicked()), actionRadioToneDecodeDisabled, SLOT(trigger()));
        QObject::connect(radioButtonSignalStrength, SIGNAL(clicked()), actionRadioSignalStrength, SLOT(trigger()));
        QObject::connect(radioButtonBlink, SIGNAL(clicked()), actionRadioButtonBlink, SLOT(trigger()));
        QObject::connect(radioButtonBreath, SIGNAL(clicked()), actionRadioButtonBreath, SLOT(trigger()));
        QObject::connect(radioButtonSparkle, SIGNAL(clicked()), actionRadioButtonSparkle, SLOT(trigger()));
        QObject::connect(radioButtonTwinkle, SIGNAL(clicked()), actionRadioButtonTwinkle, SLOT(trigger()));
        QObject::connect(ResetButton, SIGNAL(clicked()), actionResetButton, SLOT(trigger()));

        QMetaObject::connectSlotsByName(MainWindowClass);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindowClass)
    {
        actionOpen->setText(QApplication::translate("MainWindowClass", "&Import Firmware Image", 0));
#ifndef QT_NO_TOOLTIP
        actionOpen->setToolTip(QApplication::translate("MainWindowClass", "Import Firmware Image", 0));
#endif // QT_NO_TOOLTIP
        actionOpen->setShortcut(QApplication::translate("MainWindowClass", "Ctrl+O", 0));
        actionExit->setText(QApplication::translate("MainWindowClass", "E&xit", 0));
        actionExit->setShortcut(QApplication::translate("MainWindowClass", "Ctrl+Q", 0));
        actionWrite_Device->setText(QApplication::translate("MainWindowClass", "Erase/Program/Verify Device", 0));
        actionErase_Device->setText(QApplication::translate("MainWindowClass", "Erase Device", 0));
        action_About->setText(QApplication::translate("MainWindowClass", "&About", 0));
        action_Verify_Device->setText(QApplication::translate("MainWindowClass", "&Verify Device", 0));
        action_Settings->setText(QApplication::translate("MainWindowClass", "&Settings...", 0));
        actionReset_Device->setText(QApplication::translate("MainWindowClass", "Reset Device", 0));
        actionBlank_Check->setText(QApplication::translate("MainWindowClass", "Blank Check", 0));
        actionAgain->setText(QApplication::translate("MainWindowClass", "Again", 0));
        actionReadEEPROM->setText(QApplication::translate("MainWindowClass", "ReadEEPROM", 0));
#ifndef QT_NO_TOOLTIP
        actionReadEEPROM->setToolTip(QApplication::translate("MainWindowClass", "Read EEPROM", 0));
#endif // QT_NO_TOOLTIP
        actionWriteEEPROM->setText(QApplication::translate("MainWindowClass", "WriteEEPROM", 0));
#ifndef QT_NO_TOOLTIP
        actionWriteEEPROM->setToolTip(QApplication::translate("MainWindowClass", "Write to EEPROM", 0));
#endif // QT_NO_TOOLTIP
        actionRadioButtonBlink->setText(QApplication::translate("MainWindowClass", "radioButtonBlink", 0));
        actionRadioButtonBreath->setText(QApplication::translate("MainWindowClass", "radioButtonBreath", 0));
        actionRadioButtonSparkle->setText(QApplication::translate("MainWindowClass", "radioButtonSparkle", 0));
        actionRadioButtonTwinkle->setText(QApplication::translate("MainWindowClass", "radioButtonTwinkle", 0));
        actionRadioButtonToneEnable->setText(QApplication::translate("MainWindowClass", "radioButtonToneEnable", 0));
        actionRadioSignalStrength->setText(QApplication::translate("MainWindowClass", "radioSignalStrength", 0));
        actionReadFile->setText(QApplication::translate("MainWindowClass", "ReadFile", 0));
        actionSaveFile->setText(QApplication::translate("MainWindowClass", "SaveFile", 0));
        actionRadioToneDecodeDisabled->setText(QApplication::translate("MainWindowClass", "radioToneDecodeDisabled", 0));
        actionRadioButtonPWMDisable->setText(QApplication::translate("MainWindowClass", "RadioButtonPWMDisable", 0));
        actionRadioButtonPWMEnable->setText(QApplication::translate("MainWindowClass", "RadioButtonPWMEnable", 0));
        actionRadioButtonRGBEnable->setText(QApplication::translate("MainWindowClass", "RadioButtonRGBEnable", 0));
        actionResetButton->setText(QApplication::translate("MainWindowClass", "resetButton", 0));
        ReadEEPROM->setText(QApplication::translate("MainWindowClass", "  Read EEPROM", 0));
        WriteEEPROM->setText(QApplication::translate("MainWindowClass", "  Write EEPROM", 0));
        label->setText(QApplication::translate("MainWindowClass", "Firmware Version", 0));
        label_2->setText(QApplication::translate("MainWindowClass", "Radio Station Frequency", 0));
        DeviceAddress->setText(QApplication::translate("MainWindowClass", "????", 0));
        label_3->setText(QApplication::translate("MainWindowClass", "Device Address ", 0));
        label_4->setText(QApplication::translate("MainWindowClass", "Group Address 1 ", 0));
        label_5->setText(QApplication::translate("MainWindowClass", "Group Address 2", 0));
        label_6->setText(QApplication::translate("MainWindowClass", "Group Address 3", 0));
        GroupAddress1->setText(QApplication::translate("MainWindowClass", "????", 0));
        GroupAddress2->setText(QApplication::translate("MainWindowClass", "????", 0));
        GroupAddress3->setText(QApplication::translate("MainWindowClass", "????", 0));
        label_7->setText(QApplication::translate("MainWindowClass", "Tone 1", 0));
        label_8->setText(QApplication::translate("MainWindowClass", "Tone 3", 0));
        label_9->setText(QApplication::translate("MainWindowClass", "Tone 2", 0));
        Tone1->setText(QApplication::translate("MainWindowClass", "????", 0));
        Tone2->setText(QApplication::translate("MainWindowClass", "????", 0));
        Tone3->setText(QApplication::translate("MainWindowClass", "????", 0));
        label_10->setText(QApplication::translate("MainWindowClass", "Tone 5", 0));
        Tone6->setText(QApplication::translate("MainWindowClass", "????", 0));
        Tone5->setText(QApplication::translate("MainWindowClass", "????", 0));
        label_11->setText(QApplication::translate("MainWindowClass", "Tone 4", 0));
        label_12->setText(QApplication::translate("MainWindowClass", "Tone 6", 0));
        Tone4->setText(QApplication::translate("MainWindowClass", "????", 0));
        NumTones->setText(QApplication::translate("MainWindowClass", "????", 0));
        label_13->setText(QApplication::translate("MainWindowClass", "Hysteresis", 0));
        label_14->setText(QApplication::translate("MainWindowClass", "Tone Spacing", 0));
        Hysteresis->setText(QApplication::translate("MainWindowClass", "????", 0));
        ToneSpacing->setText(QApplication::translate("MainWindowClass", "????", 0));
        label_15->setText(QApplication::translate("MainWindowClass", "Threshold", 0));
        label_16->setText(QApplication::translate("MainWindowClass", "Number of Tones", 0));
        Threshold->setText(QApplication::translate("MainWindowClass", "????", 0));
        label_17->setText(QApplication::translate("MainWindowClass", "Tone Decoder Configuration", 0));
        label_18->setText(QApplication::translate("MainWindowClass", "RDS Decoder Configuration", 0));
        label_23->setText(QApplication::translate("MainWindowClass", "Output Mode", 0));
        label_24->setText(QApplication::translate("MainWindowClass", "Used for switching relay powered devices", 0));
        RadioButtonPWMDisable->setText(QApplication::translate("MainWindowClass", "On/Off Switching", 0));
        label_25->setText(QApplication::translate("MainWindowClass", "Used for Leds or variable output devices", 0));
        RadioButtonPWMEnable->setText(QApplication::translate("MainWindowClass", "PWM Switching", 0));
        label_26->setText(QApplication::translate("MainWindowClass", "Used for RGB Leds or Devices", 0));
        RadioButtonRGBEnable->setText(QApplication::translate("MainWindowClass", "RGB Output Switching ", 0));
        label_21->setText(QApplication::translate("MainWindowClass", "Which  Mode to Start in", 0));
        SaveFile->setText(QApplication::translate("MainWindowClass", "Save File", 0));
        ReadFile->setText(QApplication::translate("MainWindowClass", "Read File", 0));
        radioButtonBreath->setText(QApplication::translate("MainWindowClass", "Breath Pattern  (ms*10)", 0));
        radioButtonBlink->setText(QApplication::translate("MainWindowClass", "Blink Pattern (ms)", 0));
        label_19->setText(QApplication::translate("MainWindowClass", "On Time", 0));
        radioToneDecodeDisabled->setText(QApplication::translate("MainWindowClass", "Tone Decoding Disabled", 0));
        PatternOn->setText(QApplication::translate("MainWindowClass", "????", 0));
        radioButtonSparkle->setText(QApplication::translate("MainWindowClass", "Sparkle Pattern  ", 0));
        label_20->setText(QApplication::translate("MainWindowClass", "Off Time", 0));
        PatternOff->setText(QApplication::translate("MainWindowClass", "????", 0));
        radioButtonToneEnable->setText(QApplication::translate("MainWindowClass", "Start up in Tone Decode Mode", 0));
        radioButtonSignalStrength->setText(QApplication::translate("MainWindowClass", "Signal Strength Mode", 0));
        radioButtonTwinkle->setText(QApplication::translate("MainWindowClass", "Twinkle Pattern", 0));
        ResetButton->setText(QApplication::translate("MainWindowClass", "Reset ", 0));
        menuFile->setTitle(QApplication::translate("MainWindowClass", "&File", 0));
        menuProgrammer->setTitle(QApplication::translate("MainWindowClass", "&Program", 0));
        Q_UNUSED(MainWindowClass);
    } // retranslateUi

};

namespace Ui {
    class MainWindowClass: public Ui_MainWindowClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
